-- Then create sellers table with proper user reference
CREATE TABLE IF NOT EXISTS sellers (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    business_name VARCHAR(255) NOT NULL,
    business_slug VARCHAR(255) NOT NULL UNIQUE,
    business_description TEXT,
    business_email VARCHAR(255) NOT NULL UNIQUE,
    business_phone VARCHAR(50) NOT NULL,
    business_address TEXT NOT NULL,
    business_logo VARCHAR(512),
    business_banner VARCHAR(512),
    tax_id VARCHAR(100),
    business_registration_number VARCHAR(100),
    website_url VARCHAR(512),
    status ENUM('pending', 'approved', 'suspended', 'rejected') DEFAULT 'pending',
    rating DECIMAL(3,2) DEFAULT 0.00,
    total_products INT UNSIGNED DEFAULT 0,
    total_sales INT UNSIGNED DEFAULT 0,
    commission_rate DECIMAL(5,2) DEFAULT 0.00,
    payment_method ENUM('bank_transfer', 'paypal', 'stripe') NOT NULL,
    payment_details JSON,
    meta_title VARCHAR(255),
    meta_description TEXT,
    meta_keywords TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX (business_slug),
    INDEX (status),
    INDEX (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;